name: actions-ui
on:
  push:
    branches:
      - main
jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
        project-template: ['empty','antdv','element','quasar','vuetify']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm add -g zova-cli
      - run: zova :create:project ${{ matrix.project-template }}-${{ matrix.node-version }} --template=${{ matrix.project-template }}
      - run: cd ${{ matrix.project-template }}-${{ matrix.node-version }}
      - run: pwd
      - run: pnpm install
      - run: pwd
      - run: cat package.json
      - run: npm run build
